# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2021-01-07 21:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0002_auto_20210108_0231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testdebitsheet',
            name='batch_id',
            field=models.ForeignKey(null=True,blank=True,on_delete=django.db.models.deletion.CASCADE, to='testdb.TestDebitSheetMaster'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testdebitsheetmaster',
            name='batch_id',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
